version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: media-postgres
    environment:
      POSTGRES_DB: media
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "1211:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: media-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
